#This configuration file is used to override the use of the value.yaml variable.
#Currently, only the configuration with ingressName as nginx is provided.
#If it is another gateway such as istio or treafik, please modify the corresponding gateway requirements
image:
  # registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-web
  repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-web
  pullPolicy: Always
  tag: "preview-k8s"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim1.server.top #your hostname
      paths:
        - path: /openim-front(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls #your hostname tls
      hosts:
        - openim1.server.top
