#This configuration file is used to override the use of the value. yaml variable. You can modify it according to your own needs.
#If you modify the account information inside, it may need to be synchronized in the application file
global:
  # this is your storageClass,Please change in according to the k8s environment settings of your server
  storageClass: "nfs-client"
mode: standalone
auth:
  rootUser: root
  rootPassword: "openIM123"
defaultBuckets: "openim"
persistence:
  size: 1Gi

ingress:
  enabled: false
  ingressClassName: "nginx"
  hostname: openim.minio.console # your hostname for minioconsole
  path: /
  servicePort: minio-console
  extraTls:
    - hosts:
        - openim.minio.console
      secretName: openim2tls  #your hostname tls

apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: openim.server.com # your hostname
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /im-minio-api(/|$)(.*)
  pathType: ImplementationSpecific
  servicePort: minio-api
  extraTls:
    - hosts:
        - openim.server.com
      secretName: webapitls  #your hostname tls