
additionalPrometheusRulesMap:
  redis-mongodb-crash:
    groups:
      - name: database_insert_failure_alerts
        rules:
          - alert: DatabaseInsertFailed
            expr: (increase(msg_insert_redis_failed_total[5m]) > 0) or (increase(msg_insert_mongo_failed_total[5m]) > 0)
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Increase in MsgInsertRedisFailedCounter or MsgInsertMongoFailedCounter detected"
              description: "Either MsgInsertRedisFailedCounter or MsgInsertMongoFailedCounter has increased in the last 5 minutes, indicating failures in message insert operations to Redis or MongoDB,maybe the redis or mongodb is crash."

alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_from: 'openimalert@163.com'
      smtp_smarthost: 'smtp.163.com:465'
      smtp_auth_username: 'openimalert@163.com'
      smtp_auth_password: 'YOURAUTHCODE'
      smtp_require_tls: false
      smtp_hello: 'openim-server监控告警'
    route:
      group_by: [ 'alertname' ]
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 1h
      receiver: 'email'
    receivers:
      - name: 'email'
        email_configs:
          - to: '23937403@qq.com'
            headers: { Subject: "[WARN]告警" }
            html: '{{ template "email1" . }}'
            send_resolved: true
  templateFiles:
    template_1.tmpl: |-
      {{ define "email.to.html" }}
      {{ range .Alerts }}
      <div style="border:1px solid #ccc; padding:10px; margin-bottom:10px;">
        <h3>OpenIM Alert</h3>
        <p><strong>Alert Program:</strong> Prometheus Alert</p>
        <p><strong>Severity Level:</strong> {{ .Labels.severity }}</p>
        <p><strong>Alert Type:</strong> {{ .Labels.alertname }}</p>
        <p><strong>Affected Host:</strong> {{ .Labels.instance }}</p>
        <p><strong>Affected Service:</strong> {{ .Labels.job }}</p>
        <p><strong>Alert Subject:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Trigger Time:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
      </div>
      {{ end }}
      {{ end }}
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: { }
    labels: { }
    hosts:
      - openim4.server.top
    paths:
      - /
    tls:
      - secretName: openim4tls
        hosts:
          - openim4.server.top

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - openim2.server.top
    path: /
    tls:
      - secretName: openim2tls
        hosts:
          - openim2.server.top

prometheus:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - openim3.server.top
    paths:
      - /
    tls:
      - secretName: openim3tls
        hosts:
          - openim3.server.top