
alertmanager:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: { }
    labels: { }
    hosts:
      - openim4.server.top
    paths:
      - /
    tls:
      - secretName: openim4tls
        hosts:
          - openim4.server.top

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - openim2.server.top
    path: /
    tls:
      - secretName: openim2tls
        hosts:
          - openim2.server.top

prometheus:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - openim3.server.top
    paths:
      - /
    tls:
      - secretName: openim3tls
        hosts:
          - openim3.server.top